labs/animal_kingdom/config/routes.rb
AnimalKingdom::Application.routes.draw do

  root :to => 'home#index'

  match '/animals' => 'animals#index', :via => :get
  match '/animals/new' => 'animals#new', :via => :get
  match '/animals' => 'animals#create', :via => :post
  match '/animals/:id' => 'animals#show', :via => :get, :as => 'animal'
  match '/animals/:id/edit' => 'animals#edit', :via => :get, :as => 'edit_animal'
  match '/animals/:id' => 'animals#update', :via => :put
  match '/animals/:id/delete' => 'animals#destroy', :via => :delete, :as => 'delete_animal'

  

end

labs/animal_kingdom/app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  species    :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Animal < ActiveRecord::Base

	validates :name, :species, :photo, :presence => true 

end

labs/animal_kingdom/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
	def index
		@animals = Animal.all
	end
	def show
		animal_id = params[:id]
		@animal = Animal.find(animal_id)
	end
	def edit
		@animal = Animal.find(params[:id])
	end
	def update
		@animal = Animal.find(params[:id])

			if @animal.update_attributes(params[:animal])
				redirect_to @animal
			else
				render :edit
			end

	end

	def destroy
		animal = Animal.find(params[:id])
		animal.delete
		redirect_to animals_path	

	end

	def new
		@animal = Animal.new
	end
	def create
		@animal = Animal.new(params[:animal])

		if @animal.save
			redirect_to animals_path 
		else
			render :new 
		end
	end
end

labs/animal_kingdom/app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

end

labs/animal_kingdom/app/views/animals/_form.html.erb
<ul class='errors'>
	<% @animal.errors.full_messages.each do |error| %>
	<li><%= error %></li>
	<% end %>
</ul>

<%= form_for @animal do |f| %>

<div class='field'>
	<%= f.label :name%>
	<%= f.text_field :name%>
</div>
<div class='field'>
	<%= f.label :species%>
	<%= f.text_field :species%>
</div>
<div class='field'>
	<%= f.label :photo%>
	<%= f.text_field :photo%>
</div>
<div class='field'>
	<%= f.submit 'create animal' %>
</div>	
<% end %>

labs/animal_kingdom/app/views/animals/edit.html.erb
<h1> Edit </h1>
<%= render 'form' %>

labs/animal_kingdom/app/views/animals/index.html.erb
<ul>
<% @animals.each do |animal| %>
	<li><%= link_to animal.name, animal_path(animal) %></li>


<% end %>
</ul>

labs/animal_kingdom/app/views/animals/new.html.erb
<h1> New </h1>

<ul class='errors'>
	<% @animal.errors.full_messages.each do |error| %>
	<li><%= error %></li>
	<% end %>
</ul>

<%= form_for @animal do |f| %>

<div class='field'>
	<%= f.label :name%>
	<%= f.text_field :name%>
</div>
<div class='field'>
	<%= f.label :species%>
	<%= f.text_field :species%>
</div>
<div class='field'>
	<%= f.label :photo%>
	<%= f.text_field :photo%>
</div>
<div class='field'>
	<%= f.submit 'create animal' %>
</div>	
<% end %>

labs/animal_kingdom/app/views/animals/show.html.erb
<h1><%= link_to "delete", animal_path(@animal), :method => :delete, :confirm => "are you sure you want to do this?" %></h1>

<h1><%= link_to @animal.name, edit_animal_path(@animal) %></h1>
<p><%= @animal.species %></p>

<%= image_tag @animal.photo %>

labs/animal_kingdom/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnimalKingdom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>Animal Kingdom</header>
<nav>
	<%= link_to "Home", root_path %>
	<%= link_to "Animals", animals_path %>
	<%= link_to "New", animals_new_path %>
</nav>
<%= yield %>

<footer>(c) Animal Kingdom 2012</footer>
</body>
</html>